data = read.csv("Advertising.csv")
summary(data$TV)
summary(data$Sales)
hist(data$TV, main = "Histogram of TV")
hist(data$Sales, main = "Histogram of Sales")

sink (file = "eda-output.txt")
cat("Summary of TV")
cat("\n")
summary(data$TV)
cat("\n")
cat("Summary of Sales")
cat("\n")
summary(data$Sales)
sink()
